server:
 port: 8060
 
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
 

spring:
  application:
    name: api-gateway 
  cloud:
    gateway:
      routes:
      - id:  takeo-course
        uri: lb://takeo-course  
        predicates:
         - Path=/course/**
        
      - id:  takeo-student
        uri: lb://takeo-student
        predicates:
         - Path=/student/**
         
      - id:  identity-service
        uri: lb://identity-service
        predicates:
         - Path=/auth/**       
        
