server:
 port: 8556

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/test
  username: test
  password: test
 application:
  name: takeo-course   
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   


 
