server:
 port: 8555

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/test
  username: test
  password: test
 jpa:
  hibernate:
   ddl-auto: update
 application:
  name: takeo-student   
   
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   


 
